sudo: required
install: composer install --prefer-source


services:
  - memcache
  - docker

env: PHPAR_MYSQL=mysql://root@127.0.0.1/phpar_test PHPAR_PGSQL=pgsql://postgres@127.0.0.1/phpar_test PHPAR_MSSQL='Server=localhost;User ID=sa;Password=DockerPassword123;Database=master;Connect Timeout=30'

language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  include:
    - php: hhvm
      dist: trusty
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: 7.2
    - php: hhvm
    - php: nightly
  fast_finish: true

before_script:
  - |
    if [[ "${TRAVIS_PHP_VERSION:0:1}" == "7" ]]; then
      curl -L https://github.com/websupport-sk/pecl-memcache/archive/NON_BLOCKING_IO_php7.tar.gz | tar xz;
      (cd pecl-memcache-NON_BLOCKING_IO_php7 && phpize && ./configure && make && make install);
    fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo 'extension = "memcache.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  
  - mysql -e 'CREATE DATABASE phpar_test;'
  - psql -c 'CREATE DATABASE phpar_test;' -U postgres
  - ./test/launch-mssql-in-docker.sh -p "$MSSQL_PWD";

script: ./vendor/bin/phpunit --verbose
